### ISSUE TITLE
BaseItemTypes.dat is missing

### ISSUE THREAD

**Issue by orlp** [erosson/poedat#3]
I can't find `BaseTypeTypes.dat` in poedat's data, while some keys do reference it: https://poedat.erosson.org/pypoe/v1/tree/3.18.0e/default/ .

Is this missing for a reason or is this a bug?

**Comment by erosson** [comment]
It's a bug, but the reason's known and won't be fixed. 

Files that [PyPoE](https://github.com/OmegaK2/PyPoE) can't parse will be missing, even if other files reference them. PyPoE hasn't been updated in a very long time, so there's lots of files it can't parse anymore. 

[poe-dat-viewer](https://snosme.github.io/poe-dat-viewer/) is very good these days - I'd recommend using that instead. Compared to PyPoE, it's actually so fast/easy-to-use that I don't see any reason to keep poedat alive - so this project will be retired soon.
